[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[project]
name = "hyper_butterfly"
version = "0.1.0"
description = "하이퍼볼릭 신경망을 위한 고성능 라이브러리"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "donghwanyeom", email = "donghwanyeom@gmail.com" }]
dependencies = ["torch>=2.0.0", "numpy>=1.20.0", "matplotlib>=3.5.0"]

[project.optional-dependencies]
dev = ["pytest>=7.0.0", "black>=23.0.0", "isort>=5.12.0"]
visualization = ["plotly>=5.0.0"]

[tool.maturin]
python-source = "python"
features = ["python"]
